[package]
name = "chisel-json"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-float = "0.2.0"
chisel-decoders = "1.0.0"

[dev-dependencies]
bytesize = "1.2.0"
criterion = {version ="0.4.0", features = ["html_reports"]}
pprof = {version = "0.11.1", features = ["flamegraph", "criterion", "protobuf"]}

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "lexing"
harness = false
