[package]
name = "chisel-json"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-float = "0.2.0"
chisel-decoders = "1.0.0"

[dev-dependencies]
bytesize = "1.2.0"
criterion = "0.4.0"

[[bench]]
name = "parsing"
harness = false


[[bench]]
name = "lexing"
harness = false
