name: Chisel-Json CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cargo Make
      run: cargo install cargo-make
    - name: Make
      run: cargo make
    - name: Debug Tests
      run: cargo make test
    - name: Release Tests
      run: cargo make test-release
